reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode7.1
before_install: true
install: true
script:
- script/cibuild
notifications:
  slack:
    secure: ZGaLexVgDGkvXMwhc8IklZJHZvI7N+SN+y1YD7WBH+yCw4cc+2CtNzHzNz7TuvRQjIXVbmgcBtKUGer9kcKTfnOrzHrW6K/XdkPNB9kGRUiQf/MnpyijbWpMyf7FZZnrzrwn1mADTG8tkYjV+N5fCYePvyyD/ancurSnC2T/H8E=
branches:
  only:
  - master
env:
  matrix:
  - SCHEME="Lock-iOS" IOS_DESTINATION_VERSION="9.1" CARTHAGE_BUILD_PLATFORM="iOS"
  global:
  - secure: hU2sg0N7L2hEAXzmssJRyVGLm1cHKDwuZEE1BQy6y+9jo88926DSTZpw0uLs5h3tHWMctDt/7hoXe9D93oUQowNRaoy6Y/k34VD3Wzfbl2Dht/xZ4M2fgFwy8AYxI9Px3zLmQOewLCsAdFvoLs1rGuRcHy77RH6wtSCMJG/MVng=
  - secure: GGVKFNrp+gt0v7nTy1PRvWOt0omfSlxggpY4eDGCUvLizRNV0RrLVNxQ+5KnOSmpsC4UI7GFbTUJQhx0KTxSLEZgeaYgRHph51X0KOYxAPkYMC0eGiGzvQeT5cQldY652OKKnZLpnQsRHxdvyw8n6kMXayKxAhg4yAZIDXaSdHA=
  - secure: bsMF0Xg/eq+rW52vm+NqaiZi8DJd3GtVXZY43zsl9lbD6L8oMtihEndyWJHHg/BT6iHIs3ITOrGfwqGft4+tro3I8c1CflWD8gvPsalYh3/TQ2rQog1zlv5JCCCojV8GXmCOgefpawttVkEwYD7JRcAhReDT4ixSMWM6Kx0rqB4=
  - secure: CRMo92c50yRpN+zaSfAvPq/kgVwxZQ6KkDYguZdBRv4/kIk1yVgh2osegLXwPgEGN+Bt8TtDscI5u2yWFYQBPrR7Ma+mIF3sls7sFeJiawcITcRLfJMMDP6JfdXO4nM1hTEIrOeAjHXWTNy9fVuWH6MDbMMpX0/1rEKlXMiN72s=