version: 2.1

executors:
  job-environment:
    shell: /bin/bash --login -eo pipefail
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      HOMEBREW_LOGS: ~/homebrew-logs
      HOMEBREW_TEMP: ~/homebrew-temp
      HOMEBREW_NO_AUTO_UPDATE: 1
      SCHEME: Lock
      DEVICE: iPhone 11
      FASTLANE_EXPLICIT_OPEN_SIMULATOR: 2

commands:
  use-swift:
    parameters:
      version: 
        type: string
    steps: 
      - run: sed -i "" 's/SWIFT_VERSION = 5.0/SWIFT_VERSION = << parameters.version >>/g' "Lock.xcodeproj/project.pbxproj"
  prepare:
    parameters:
      ruby:
        type: string
        default: "2.6.3"
    steps:
      - restore_cache:
          keys:
          - lock-swift-gems-{{ checksum "Gemfile.lock" }}
          - lock-swift-gems-
      - run: |
          echo "ruby-<< parameters.ruby >>" > ~/.ruby-version
          bundle check || bundle install --without=development
      - save_cache:
          key: lock-swift-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: |
          brew install swiftlint
          grep -lR "shouldUseLaunchSchemeArgsEnv" *.* --null | xargs -0 sed -i '' -e 's/shouldUseLaunchSchemeArgsEnv = "YES"/shouldUseLaunchSchemeArgsEnv = "YES" codeCoverageEnabled = "YES"/g'
      - restore_cache:
          keys:
            - lock-swift-carthage-{ checksum "Cartfile.resolved" }}
            - lock-swift-carthage-
      - run: |
          bundle exec fastlane ios bootstrap
      - save_cache:
          key: lock-swift-carthage-{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage/Build
  build:
    steps:
      - run: |
          carthage build --no-skip-current
  test:
    steps: 
      - run: |
          bundle exec fastlane ios ci
  pod-lint:
    steps:
      - run: |
          bundle exec fastlane ios pod_lint
  send-coverage-report:
    steps:
      - run: bash <(curl -s https://codecov.io/bash) -J 'Lock'

jobs:
  build-and-test-swift-5_2:
    executor: job-environment
    macos:
      xcode: 11.7.0
    steps:
      - checkout
      - prepare:
          ruby: "2.7.1p83"
      - build
      - test
      - send-coverage-report
      - pod-lint
      - store_test_results:
          path: fastlane/test_output
  build-and-test-swift-5_0:
    executor: job-environment
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - prepare
      - build
      - test
  build-and-test-swift-4_2:
    executor: job-environment
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - use-swift: 
          version: "4.2"
      - prepare
      - build
      - test
  build-and-test-swift-4_0:
    executor: job-environment
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - use-swift: 
          version: "4.0"
      - prepare
      - build
      - test

workflows:
  build:
    jobs:
      -  build-and-test-swift-5_2
      -  build-and-test-swift-5_0
      -  build-and-test-swift-4_2
      -  build-and-test-swift-4_0
